### ISSUE TITLE
/usr/bin/../share/nmap/nselib/packet2.lua:39: bad argument #1 to 'byte

### ISSUE THREAD

**Issue by vah13** [fireeye/synfulknock#1]
--------------- Timing report ---------------
  hostgroups: min 1, max 100000
  rtt-timeouts: init 500, min 100, max 1250
  max-scan-delay: TCP 10, UDP 1000, SCTP 10
  parallelism: min 0, max 0
  max-retries: 6, host-timeout: 0
##   min-rate: 0, max-rate: 0

NSE: Using Lua 5.2.
NSE: Arguments from CLI: 
NSE: Loaded 1 scripts for scanning.
NSE: Script Pre-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 18:16
Completed NSE at 18:16, 0.00s elapsed
Initiating SYN Stealth Scan at 18:16
Scanning ip [1 port]
Packet capture filter (device venet0): dst host ip and (icmp or icmp6 or ((tcp or udp or sctp) and (src host ip)))
Discovered open port 80/tcp on ip
Increased max_successful_tryno for ip to 1 (packet drop)
Completed SYN Stealth Scan at 18:16, 0.64s elapsed (1 total ports)
Overall sending rates: 3.15 packets / s, 138.44 bytes / s.
NSE: Script scanning 37.187.114.171.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 18:16
NSE: Starting synfulknock against ip:80.
NSE: synfulknock against ip:80 threw an error!
/usr/bin/../share/nmap/nselib/packet2.lua:39: bad argument #1 to 'byte' (string expected, got nil)
stack traceback:
    [C]: in function 'byte'
    /usr/bin/../share/nmap/nselib/packet2.lua:39: in function 'u32'
    /usr/bin/../share/nmap/scripts/synfulknock.nse:86: in function 'processresponse'
    /usr/bin/../share/nmap/scripts/synfulknock.nse:174: in function </usr/bin/../share/nmap/scripts/synfulknock.nse:148>
    (...tail calls...)

Completed NSE at 18:16, 0.31s elapsed
Nmap scan report for ip
Host is up, received user-set (0.057s latency).
Scanned at 2015-09-16 18:16:36 MSK for 1s
PORT   STATE SERVICE REASON
80/tcp open  http    syn-ack ttl 56
Final times for host: srtt: 56634 rttvar: 56634  to: 283170

NSE: Script Post-scanning.
NSE: Starting runlevel 1 (of 1) scan.
Initiating NSE at 18:16
Completed NSE at 18:16, 0.00s elapsed
Read from /usr/bin/../share/nmap: nmap-payloads nmap-services.
Nmap done: 1 IP address (1 host up) scanned in 1.34 seconds
           Raw packets sent: 3 (132B) | Rcvd: 1 (44B)

**Comment by vah13** [comment]
if 80 port is down then will get this debug trace

**Comment by TonyLeeVT** [comment]
Can you try running the NSE script on a Kali 2.0 VM and let us know if you have the same issue.

**Comment by TonyLeeVT** [comment]
Just to clarify on the the scenario because "down" could mean a few things:
- Host did not exist
- Port was closed
- Port was filtered

Do you receive that error on all of the above or only certain scenarios?
Also, have you tried running this from Kali 2.0?  If not, what is your setup?
If the ranges are reasonable, you could also use the Python script.  Have you tried that?

**Comment by Gudik** [comment]
I am getting the exact same error on a Kali 2.0 full patched VM. 

...
NSE: SYNfulKnock against 172.xx.xx.xx:80 threw an error!
/usr/bin/../share/nmap/nselib/packet2.lua:39: bad argument #1 to 'byte' (string expected, got nil)
stack traceback:
    [C]: in function 'byte'
    /usr/bin/../share/nmap/nselib/packet2.lua:39: in function 'u32'
    /usr/bin/../share/nmap/scripts/SYNfulKnock.nse:86: in function 'processresponse'
    /usr/bin/../share/nmap/scripts/SYNfulKnock.nse:174: in function </usr/bin/../share/nmap/scripts/SYNfulKnock.nse:148>
    (...tail calls...)

...

Nmap scan report for 172.xx.xx.xx
Host is up, received user-set (0.011s latency).
Scanned at 2015-09-17 13:17:18 EDT for 6s
PORT   STATE SERVICE REASON
80/tcp open  http    syn-ack ttl 128
Final times for host: srtt: 10622 rttvar: 10622  to: 100000

The script was successful for a number of hosts in a c class network, but failing on a number of them. 

The host is a debian host running a Apache web server.

**Comment by aalborz** [comment]
Running this ok Kali from nmap I get : " 80/tcp open http |_synfulknock: ERROR: Script execution failed (use -d to debug)" on lot of devices. 
I've tried python script also. It successfully runs the commands, but not getting anything on the screen. So how would I know if any device is or isn't vulnerable?

**Comment by TonyLeeVT** [comment]
I think I know what is causing the issue.  If you have a publicly available system that consistently responds that way I can troubleshoot it and fix it.  Email me at synfulknock [at] fireeye.com if you have such a system.

The upside is that they failure most likely indicates that the system is not vulnerable because the response was not what the tool is seeking.

A good second check is to run the python script.  If that runs and you do not see anything like the following then you are not vulnerable:
"2015-07-14 12:59:03,188 110 INFO 10.1.1.1:80 - Found implant seq: 667f6e09 ack: 66735bcd"

**Comment by TonyLeeVT** [comment]
The latest version of the script contains error checking.  It will gracefully report when layer3 is nil.  When that occurs, use the python script.  This should be minimal when it occurs.  We are looking into the root cause though.

**Comment by TonyLeeVT** [comment]
I believe I have figured out the issue...  but there may not be a clean way to solve it.  Explanation is below:

The nmap scan occurs in 2 stages:
1)  Nmap -sS checks to see if the port is open
2)  If the port is open, NSE sends the specially crafted SYN packet and looks for the implant response

So in a packet capture you would see at least 6 packets:
1)  SYN -> SYN/ACK -> RST
2)  SYN -> SYN/ACK -> RST

Some servers seem a bit slow to respond on the second (NSE) scan though...  thus we see:
1)  SYN -> SYN/ACK -> RST
2)  SYN -> [Nothing]

That lack of a quick response from the server is what causes layer3 to be nil.  The NSE script closes the socket before the server slowly responds.

There may be a few long term solutions:
1)  Convert the script to a prerule script
2)  Insert a delay to wait for the server response
3)  Use nmap to scan first and feed the hosts with an error into the python script

We currently handle the error better than before, but will revisit it to hopefully provide a cleaner long term solution.  Thanks for reporting.

**Comment by aalborz** [comment]
I downloaded & ran the latest nmap script. It still showed "_synfulknock: ERROR: Script execution failed". However, I ran the python script & it didn't come back with any "Found implant" result, so looks like we're all good. Thanks!

**Comment by TonyLeeVT** [comment]
We had some feedback on using nmap 6.47 and 6.49 BETA.  The feedback has been that 6.47 may be more reliable.  This version ships preinstalled with Kali 1.1.0.  I updated the readme to reflect that information.  In the mean time, I will work with the nmap folks to get the tool and library properly integrated.  Qualys and Nessus also have plugins to check for this as well.  Thanks.
