### ISSUE TITLE
SYNfulKnock.nse:4: unexpected symbol near '<'

### ISSUE THREAD

**Issue by sandroded** [fireeye/synfulknock#2]
nmap -sS -PN -n -T4 -p 80 --script="SYNfulKnock" 10.1.1.1/24

Starting Nmap 6.49BETA4 ( https://nmap.org ) at 2015-09-25 04:44 EDT
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:254: /usr/bin/../share/nmap/scripts/SYNfulKnock.nse:4: unexpected symbol near '<'
stack traceback:
    [C]: in function 'assert'
    /usr/bin/../share/nmap/nse_main.lua:254: in function 'loadscript'
    /usr/bin/../share/nmap/nse_main.lua:582: in function 'new'
    /usr/bin/../share/nmap/nse_main.lua:805: in function 'get_chosen_scripts'
    /usr/bin/../share/nmap/nse_main.lua:1249: in main chunk
    [C]: in ?

QUITTING!

The same error on Kali 2.0 VM and Ubuntu 14.04.

**Comment by TonyLeeVT** [comment]
Did you verify that the file download was successful?  Maybe vim or emacs the nse script to make sure it is not an HTML file starting with a '<' character?  Just a guess on this one as I have never seen that error before.

**Comment by sandroded** [comment]
Thank you. It was HTML inside.

**Comment by TonyLeeVT** [comment]
Sure thing.  Just a reminder to everyone that you can either download the zip file or use git from the command line.  Example shown below:

git clone https://github.com/fireeye/synfulknock.git
